#= require jquery
#= require jquery_ujs
#= require underscore-min
#= require selectize
#= require twitter/typeahead
#= require s3_direct_upload
#= require logbook/search
#= require logbook/enhance
#= require_self
